version: '3.8'

services:
  postgres:
    image: postgres:13.3-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - auth_backend

  redis:
    image: redis:7.2.0
    ports:
      - "6379:6379"
    volumes:
      - rd_data:/data
    networks:
      - auth_backend

  auth_backend:
    build:
      context: src
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - auth_backend

  tests:
    build:
      context: tests/functional
    entrypoint: >
      sh -c "
        pytest src
      "
    env_file: .env
    networks:
      - auth_backend


volumes:
  pg_data:
  rd_data:

networks:
  auth_backend:
    name: auth_backend