"""init migration

Revision ID: 04868df744f3
Revises: 
Create Date: 2024-03-07 16:24:41.605768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "04868df744f3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("is_revoked", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("issued_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="refresh_tokens_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="refresh_tokens_pkey"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=320), autoincrement=False, nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_table(
        "login_histories",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("useragent", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
        sa.Column("remote_addr", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("referer", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="login_histories_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="login_histories_pkey"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("login_histories")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###
